// API服务导出
export * from './api'
export * from './auth'
export * from './user'
export * from './upload'
export * from './scales'
export * from './popular-majors'
export * from './provinces'
export * from './majors'
export * from './scores'
export * from './choices'
export * from './enroll-plan'
export * from './exam-info'